#!/bin/sh

# This pile of horror converts the makefiles into expecting the -export
# version of the libraries.

set -e
cd build-udeb

for lib in dns irs isc isccc isccfg lwres; do
    sed -i "s/lib${lib}\./lib${lib}-export./g" lib/${lib}/Makefile
done

patch -p2 < ../debian/export.diff

for lib in dns irs isc isccc isccfg lwres; do
    sed -i 's/\(lib'${lib}'\).la/\1-export.la/g'  $(find . -name Makefile)
done
