#!/bin/sh

set -e

#DEBHELPER#

if [ "$1" = "purge" ]; then
	rm -f /etc/bind/rndc.key /etc/bind/named.conf.options /etc/default/bind9
	rmdir /etc/bind >/dev/null 2>&1 || true
	rm -f /etc/apparmor.d/force-complain/usr.sbin.named >/dev/null 2>&1 || true
	rm -f /var/lib/bind/bind9-default.md5sum
	rmdir /var/lib/bind
	# delete bind daemon user, if it exists
	if getent passwd bind > /dev/null ; then
		deluser  --quiet bind > /dev/null || true
	fi
fi

exit 0
